-- V059: 중복 인덱스 ix_articles_complex_no 제거 (24MB 회수 — 세션 406)
--
-- 배경: articles 에 complex_no 선행 인덱스가 3개 겹쳐 있었다.
--   ix_articles_complex_no        (complex_no)                                  24MB
--   ix_articles_complex_active    (complex_no, is_active)                       24MB
--   idx_articles_confirm_sort     (complex_no, is_active, article_confirm_ymd)  26MB
-- B-tree 는 선행 칼럼만으로도 검색되므로 1칼럼짜리는 나머지 둘에 완전히 포섭된다.
-- 쓰기마다 3개를 다 갱신하는데(articles 는 크롤러가 상시 upsert/update 하는 테이블)
-- 그중 하나는 읽기에 기여하지 않는다.
--
-- ── 제거해도 되는 근거 (세션 406 prod 실측) ─────────────────────────────────
--
-- ⚠ 아래 근거는 세션 406 이 적었고, **같은 세션의 적대검증·할루시네이션 감사에서
--    3건이 사실과 다르다고 적발돼 정정한 판**이다. 원래 서술은 "전부/0건/동일" 같은
--    단정어를 썼는데 실제로는 반례가 있었다. 결론(제거해도 안전)은 반박 실패로
--    유지됐으나, 근거 문장을 그대로 믿고 인용하지 말 것.
--
-- (1) 앱 쿼리 플랜 불변. 트랜잭션 안에서 DROP → EXPLAIN → ROLLBACK 으로 대조.
--     세션 406 이 단지 15111(13행)로 측정한 값은 count cost≈8.85 / 목록 cost≈88.84 가
--     제거 전후 동일이었다.
--     ⚠ 이 수치는 **재현 불가**로 판정됐다(감사 결과): 인덱스가 이미 삭제돼 "있을 때"를
--     다시 잴 수 없고, 45개 단지 재측정에서 count 8.91 / 목록 84.63 등 다른 값이 나왔다.
--     통계 갱신(ANALYZE)으로 설명 가능한 폭이라 조작으로 보지는 않으나, **이 숫자를
--     근거로 재인용하지 말 것.** 플랜 불변 자체는 아래 (2)(5)로 뒷받침된다.
--
-- (2) complex_no 를 **단독으로** 거르는 앱 경로는 services/upsert.py
--     delete_missing_articles(complex_no + article_no NOT IN ...) 하나이고, 이 쿼리는
--     제거 전후 모두 포섭 인덱스로 간다.
--     ⚠ 원래 "idx_articles_confirm_sort (제거 전후 동일)"이라고 단정했으나 **틀렸다**:
--     단지 크기에 따라 플래너가 갈린다 — 189717(4,994행)은 ix_articles_complex_active,
--     15352(103행)은 idx_articles_confirm_sort. 어느 쪽이든 포섭 인덱스라 결론은 같다.
--
-- (3) 코드 전수 확인: Article 을 complex_no 로 거르는 곳은 전부 is_active 와 짝이다
--     (article_queries.py:26-27 · complex_queries.py:74,101 · stats_queries.py:29,38 ·
--      _detail_worker.py:25-32 · _crawl_bg.py:99 · service_discover.py:219 ·
--      price_queries.py:188-192 는 is_active 로 시작하는 조건 목록에 덧붙임).
--     이 file:line 인용 8곳은 감사에서 **전부 정확**으로 확인됐다(직접 읽고 적은 것).
--     적대검증이 raw SQL 3곳(price_queries.py:44,78 · stats_queries.py:50)까지 추가로
--     훑었고 역시 전부 is_active 와 짝 — 반례 0건.
--
-- (4) 공유 DB(mibunyang) 영향 0.
--     ⚠ 원래 "PostgREST 상위 쿼리에 complex_no 단독 필터 **0건**"이라고 적었으나
--     **거짓이다**: PostgREST 경유 + complex_no + is_active 없음 = 실측 5~7종·수십 회가
--     실재한다(`SELECT ... FROM articles WHERE complex_no = $1 LIMIT ...` 형태).
--     다만 **전부 complex_no 가 선행 칼럼**이라 ix_articles_complex_active 가 그대로
--     흡수한다(EXPLAIN: Index Only Scan using ix_articles_complex_active) — 영향 0 이라는
--     결론은 유지되나, 근거는 "그런 쿼리가 없다"가 아니라 "있어도 포섭된다"이다.
--     articles 에 외래키 제약 0개는 참(pg_constraint 확인).
--
-- (5) 대형 단지 재검증(적대검증, 단지 134062 = 7,974행): count·목록·DELETE 세 형태 모두
--     Index Only/Bitmap Index Scan 으로 처리되고 Seq Scan 폴백 0건.
--
-- ⚠ idx_scan 이 95,343(통계창 2026-08-24~, 하루 약 4,373회)으로 non-zero 인 것은
--    맞다. 그러나 그 호출들은 인덱스가 없으면 포섭 인덱스로 흡수된다 —
--    "쓰인 적 있다"와 "없으면 안 된다"는 다르다.
--    (이 수치 자체는 인덱스 삭제와 함께 통계도 사라져 **재현 불가**. 통계창 시각과
--     일일 환산은 감사에서 참으로 확인됐다.)
--
-- ── ORM 동반 수정 (이 파일만 적용하면 반쪽이다) ─────────────────────────────
--
-- 이 인덱스의 진짜 출처는 db/models.py 의 Article.complex_no 에 붙은 index=True 다.
-- tests/conftest.py 가 Base.metadata.create_all() 로 스키마를 만들므로, SQL 만
-- 적용하고 ORM 선언을 두면 테스트 환경에서 계속 재생성된다. 같은 커밋에서
-- index=True 를 제거했다(tests/test_migration_v059_drop_redundant_idx.py 가 가드).
--
-- ── prod 적용 ───────────────────────────────────────────────────────────────
--
-- DROP INDEX CONCURRENTLY 는 락 0·무중단이고 backend 재시작과 무관하다(V050·V057 선례).
--
-- ⚠ 연결 만드는 법에서 두 번 막힌다 (세션 406 실측 — 아래 ✓ 형태를 그대로 쓸 것).
--    이 문은 트랜잭션 블록 안에서 실행 자체가 불가능한데, 이 레포의 평소 연결 경로로는
--    트랜잭션을 벗어나기가 생각보다 까다롭다:
--
--      ✗ engine.raw_connection() → raw.set_session(autocommit=True)
--        "set_session cannot be used inside a transaction" (raw_connection 이 이미 트랜잭션 안)
--      ✗ raw.rollback() → raw.autocommit = True → SET statement_timeout ...
--        SET 이 트랜잭션을 다시 열어 DROP 에서
--        "DROP INDEX CONCURRENTLY cannot run inside a transaction block"
--      ✓ 별도 엔진 + AUTOCOMMIT + **서버측 옵션으로 timeout 지정**(SET 문을 아예 안 쓴다)
--
--    성공한 형태 (backend/ cwd, PYTHONPATH=.):
--      from sqlalchemy import create_engine
--      from db.database import DATABASE_URL
--      eng = create_engine(
--          DATABASE_URL,
--          isolation_level="AUTOCOMMIT",
--          connect_args={"options": "-c statement_timeout=600000"},  # SET 대신 이것
--      )
--      with eng.connect() as conn:
--          conn.exec_driver_sql("DROP INDEX CONCURRENTLY IF EXISTS ix_articles_complex_no")
--
--    connect_args 로 넘기는 이유 = db/database.py connect 이벤트가 연결마다
--    statement_timeout=8000 을 박는데, 그걸 SET 으로 풀면 트랜잭션이 열려 위 ✗ 가 된다.
--    (Supavisor 풀러가 startup options 를 무시할 수 있다 — infra.md §statement_timeout.
--     세션 406 실측에서 SHOW 는 2min 으로 보였으나 DROP 이 0.0초라 무관했다.)
--
-- ⚠ running 잡이 없는 시점에 하면 즉시 끝난다(세션 406: 0.0초). 잡이 돌고 있어도
--    CONCURRENTLY 는 그 잡을 끊지 않고 기다렸다 지운다 — 재시작과 달리 중단 위험 0.
--
-- 적용 후 확인:
--   SELECT indexrelname, idx_scan FROM pg_stat_user_indexes WHERE relname='articles';
--   -- ix_articles_complex_no 행이 사라지고, complex_active/confirm_sort 는 그대로여야 한다.
--   SELECT pg_size_pretty(pg_indexes_size('articles'));  -- 292MB → 약 268MB 기대
--
-- 본 파일 본문은 멱등·비-CONCURRENTLY (CI 는 SQLite 라 미실행, 문서·재현용 — V050/V057 관례).

DROP INDEX IF EXISTS ix_articles_complex_no;

-- 역방향 (롤백 — prod 은 CONCURRENTLY 로 락 0. 트랜잭션 블록 안 실행 불가 → autocommit):
-- CREATE INDEX CONCURRENTLY IF NOT EXISTS ix_articles_complex_no ON articles (complex_no);
-- 롤백 시 db/models.py 의 index=True 도 함께 되돌릴 것.
